### PR TITLE
Misc. typo

### PR DESCRIPTION
**Pull request by luzpaz**
super trivial source comment typo ;)

### CODE REVIEW

**Comment by luzpaz** [comment]
I'm opting out of signing. I don't need attribution.

**Comment by oddhack** [comment]
That's not something you can opt out of. Khronos requires accepting the CLA before we will merge outside contributions to our repos.

**Comment by luzpaz** [comment]
@oddhack signed. green light

**Comment by luzpaz** [comment]
@oddhack please review when you get a moment. thanks

**Comment by oddhack** [comment]
We're in the middle of moving the C++ spec into asciidoctor from asciidoc, and this typo got fixed in the process - thanks for catching it - along with many other minor fixes. Hopefully the updated specs will be published in the near future, depending on how many cycles the WG members have available  to review and sign off; in the meantime, we're probably not going to issue an update of the current spec just to fix a typo.

**Pull request closed without merging**
